- name: validator
  hosts: localhost
  connection: local
  tasks:
  - name: validate docker container
    uri:
      url: http://webservers:8080
      return_content: yes
    register: this
    failed_when: "'hey there' not in this.content"
